### ISSUE TITLE
想请问下为什么用这个还需要依赖rtt的串口驱动呢

### ISSUE THREAD

**Issue by samuelyhsu** [supperthomas/RTTHREAD_SEGGER_TOOL#27]

**Comment by supperthomas** [comment]
console 是基于serial device的。

**Comment by uplume** [comment]
测试发现有时打印会丢失，是segger rtt本身原理导致的吗

**Comment by samuelyhsu** [comment]
测试发现有时打印会丢失，是segger rtt本身原理导致的吗

**Comment by supperthomas** [comment]
> 测试发现有时打印会丢失，是segger rtt本身原理导致的吗

有可能是buffer size不够大，如果rtt里面的log长时间PC不去取的话，log会覆盖掉之前的。

**Comment by samuelyhsu** [comment]
非常感谢 增大上行buf大小 BUFFER_SIZE_UP 确实就正常了
