### ISSUE TITLE
RTT_DEFAULT_TERMINAL_INDEX和RTT_DEFAULT_BUFFER_INDEX

### ISSUE THREAD

**Issue by wangchaoHZ** [supperthomas/RTTHREAD_SEGGER_TOOL#28]
请问源码里**RTT_DEFAULT_TERMINAL_INDEX**和**RTT_DEFAULT_BUFFER_INDEX**这两个宏的定义是什么？没找到定义地方，谢谢啦

**Comment by supperthomas** [comment]
在rtconfig.h里面

**Comment by wangchaoHZ** [comment]
> 在rtconfig.h里面

您好，我仔细查看了一下，在本仓库的主分支内，是没有rtconfig.h文件的，可否更新一下？

**Comment by supperthomas** [comment]
![image](https://github.com/supperthomas/RTTHREAD_SEGGER_TOOL/assets/60349489/30c5c3cf-68b6-4410-96cf-d6dc6bec1061)

你是用的RTTHREAD吗？
直接menuconfig就可以了，pkgs --upgrade和pkgs --update执行一下。
