### ISSUE TITLE
>RTT5.1.0 串口V2编译报错

### ISSUE THREAD

**Issue by wdfk-prog** [supperthomas/RTTHREAD_SEGGER_TOOL#31]
![image](https://github.com/user-attachments/assets/f77bd453-86e6-496a-9962-80e8cbdd5fb2)

- 修改`rt_size_t ` 为 `rt_ssize_t `解决,不知道需不需要加版本判断
```c
static rt_ssize_t mcu_transmit(struct rt_serial_device     *serial,
```

**Comment by supperthomas** [comment]
欢迎PR一下
